# A comprehensive list of cliches and tired phrases.
# Sourced from various online writing resources.

CLICHES = [
    "'tis the season",
    "20/20 hindsight",
    "Achilles' heel",
    "Badonkadonk",
    "E-ticket",
    "I beg to differ",
    "I smell a rat",
    "I'm okay, you're okay",
    "Jack of all trades",
    "Johnny-come-lately",
    "King's English",
    "Monday morning quarterback",
    "Rome wasn't built in a day",
    "a bad egg",
    "a bed of roses",
    "a bee in your bonnet",
    "a bird in the hand is worth two in the bush",
    "a blast from the past",
    "a blot on the landscape",
    "a bolt from the blue",
    "a bull in a china shop",
    "a chain is only as strong as its weakest link",
    "a chip off the old block",
    "a diamond in the rough",
    "a drop in the bucket",
    "a far cry",
    "a few sandwiches short of a picnic",
    "a fish out of water",
    "a fly in the ointment",
    "a fool and his money are soon parted",
    "a gut feeling",
    "a heart of gold",
    "a knight in shining armor",
    "a leopard can't change its spots",
    "a light at the end of the tunnel",
    "a necessary evil",
    "a pain in the neck",
    "a penny for your thoughts",
    "a penny saved is a penny earned",
    "a picture is worth a thousand words",
    "a piece of cake",
    "a race against time",
    "a rainy day",
    "a ray of sunshine",
    "a sea of faces",
    "a silver lining",
    "a slap on the wrist",
    "a slippery slope",
    "a stitch in time saves nine",
    "a storm in a teacup",
    "a taste of your own medicine",
    "a tough row to hoe",
    "a wolf in sheep's clothing",
    "ace in the hole",
    "ace up his sleeve",
    "ace up your sleeve",
    "acid test",
    "add insult to injury",
    "afraid of his own shadow",
    "against all odds",
    "air your dirty laundry",
    "airing dirty laundry",
    "all booster, no payload",
    "all foam, no beer",
    "all fun and games",
    "all hammer, no nail",
    "all hat, no cattle",
    "all icing, no cake",
    "all in a day's work",
    "all lime and salt, no tequila.",
    "all missile, no warhead",
    "all shot, no powder",
    "all sizzle, no steak",
    "all talk, no action",
    "all that and a bag of chips",
    "all thumbs",
    "all wax and no wick",
    "all wet",
    "all's fair in love and war",
    "all's well that ends well",
    "almighty dollar",
    "always a bridesmaid",
    "ambulance chaser",
    "an axe to grind",
    "an elephant in the room",
    "an uphill battle",
    "another day, another dollar",
    "ants in your pants",
    "apple-pie order",
    "arm and a leg",
    "armchair quarterback",
    "armed to the teeth",
    "army brat",
    "art imitates life",
    "artsy-craftsy",
    "artsy-fartsy",
    "as cool as a cucumber",
    "as good as gold",
    "as happy as a clam",
    "as luck would have it",
    "as old as the hills",
    "as old as time",
    "as plain as the nose on your face",
    "as white as a sheet",
    "at loggerheads",
    "at the end of the day",
    "at the end of your rope",
    "avoid like the plague",
    "babe in the woods",
    "back against the wall",
    "back in the saddle",
    "back to square one",
    "back to the drawing board",
    "bad to the bone",
    "badge of honor",
    "ballpark figure",
    "balls to the wall",
    "banging your head against a brick wall",
    "baptism of fire",
    "bare bones",
    "bark is worse than the bite",
    "bark up the wrong tree",
    "barking up the wrong tree",
    "bat out of hell",
    "bats in the belfry",
    "batten down the hatches",
    "battle royal",
    "beat a dead horse",
    "beat around the bush",
    "beat the bushes",
    "beats me",
    "beauty is in the eye of the beholder",
    "beauty is only skin deep",
    "beggars can't be choosers",
    "behind every great man there's a great woman",
    "behind the eight ball",
    "bend over backwards",
    "bent out of shape",
    "best foot forward",
    "bet your bottom dollar",
    "better half",
    "better late than never",
    "better mousetrap",
    "better safe than sorry",
    "better than ever",
    "better the Devil you know",
    "between a rock and a hard place",
    "beyond the pale",
    "bib and tucker",
    "big as a house",
    "big as life",
    "big fish in a small pond",
    "big man on campus",
    "bigger they are the",
    "bigger they are, the harder they fall",
    "bird in the hand",
    "birds and the bees",
    "birds of the feather",
    "bite the bullet",
    "bite the dust",
    "bite your tongue",
    "biting the hand that feeds you",
    "bitter disappointment",
    "black as coal",
    "black as pitch",
    "blast from the past",
    "bleeding heart",
    "blessing in disguise",
    "blind as a bat",
    "blood is thicker than water",
    "blood money",
    "blood on your hands",
    "blood sweat and tears",
    "blood, sweat, and tears",
    "blow off some steam",
    "blow this pop stand / joint",
    "blushing bride",
    "boil it down to",
    "bone dry",
    "bone of contention",
    "booze and broads",
    "bored to tears",
    "born and raised",
    "born with a silver spoon in your mouth",
    "born yesterday",
    "bottom line",
    "boys will be boys",
    "brain drain",
    "brain dump",
    "brass tacks",
    "break a leg",
    "bright and early",
    "bring home the bacon",
    "broken record",
    "brother's keeper (thy)",
    "bull by the horns",
    "bull in a china shop",
    "bump in the night",
    "burn the midnight oil",
    "burning bridges",
    "bury the hatchet",
    "busy as a bee",
    "but seriously",
    "by and large",
    "by the skin of your teeth",
    "call it a day",
    "calm before the storm",
    "can of worms",
    "can't cut the mustard",
    "can't judge a book by its cover",
    "candle at both ends",
    "case of mistaken identity",
    "cat got your tongue",
    "cat got your tongue?",
    "cat out of the bag",
    "caught between a rock and a hard place",
    "caught red-handed",
    "chapter and verse",
    "charity begins at home",
    "chasing rainbows",
    "checkered career",
    "chew the fat",
    "chickens come home to roost",
    "chip on your shoulder",
    "chomping at the bit",
    "clean slate",
    "cleanliness is next to godliness",
    "clear as a bell",
    "clear as mud",
    "close but no cigar",
    "cloud nine",
    "cold feet",
    "cold shoulder",
    "come hell or high water",
    "communist conspiracy",
    "conniption fit",
    "cool as a cucumber",
    "could care less",
    "couldn't care less",
    "couldn't get to first base",
    "count your blessings",
    "count your chickens before they hatch",
    "countless hours",
    "cream of the crop",
    "creature comfort",
    "crime in the street",
    "crystal clear",
    "curiosity killed the cat",
    "curry favor",
    "cut a fine figure",
    "cut and dried",
    "cut to the chase",
    "cut to the quick",
    "cute as a button",
    "dark and stormy night",
    "darkest before the dawn",
    "dead as a doornail",
    "death and destruction",
    "death and taxes",
    "death's doorstep",
    "devil is in the details",
    "diamond in the rough",
    "dim view",
    "dog days",
    "dog in the manger",
    "don't burn your bridges",
    "don't count your chickens before they're hatched",
    "don't cry over spilt milk",
    "don't do the crime if you can't do the time",
    "don't get your knickers in a twist",
    "don't look a gift horse in the mouth",
    "don't put all your eggs in one basket",
    "doubting Thomas",
    "down and dirty",
    "down in the dumps",
    "down pat",
    "down the drain/toilet",
    "down the hatch",
    "down to earth",
    "draining the swamp",
    "drink like a fish",
    "drive me up the wall",
    "drive you up a wall",
    "dull as dishwater",
    "dutch uncle",
    "dyed in the wool",
    "eagle eye",
    "ear to the ground",
    "early bird catches the worm",
    "easier said than done",
    "easy as 1-2-3",
    "easy as pie",
    "eat crow",
    "eat humble pie",
    "eat like a bird",
    "eat like a horse",
    "eleventh hour",
    "enough already",
    "even money",
    "every cloud has a silver lining",
    "every dog has its day",
    "every fiber of my being",
    "every man has his price",
    "everything but the kitchen sink",
    "evil twin",
    "existential angst",
    "experts agree",
    "eye for an eye",
    "face the music",
    "facts of life",
    "fair weather friend",
    "fair-haired one",
    "fall off of a turnip truck",
    "fall on deaf ears",
    "famous last words",
    "fat cat",
    "fat slob",
    "favor us with a song",
    "fear and loathing",
    "feast or famine",
    "feather in your cap",
    "feather your nest",
    "fellow traveler",
    "few and far between",
    "field this one",
    "fifteen minutes of fame",
    "fight fire with fire",
    "fish nor fowl",
    "fit as a fiddle",
    "flat as a pancake",
    "flesh and blood",
    "fly by night",
    "fly by the seat of your pants",
    "fly off the handle",
    "fly the coop",
    "follow your heart",
    "for the birds",
    "forgive and forget",
    "fox in the henhouse",
    "free as a bird",
    "fresh as a daisy",
    "freudian slip",
    "full circle",
    "fun and games",
    "fun in the sun",
    "garbage in, garbage out",
    "gentle as a lamb",
    "get a grip",
    "get down to brass tacks",
    "get the sack",
    "get your feet wet",
    "get your groove back",
    "gets my goat",
    "gift horse in the mouth",
    "gilding the lily",
    "give a damn",
    "give it a whirl",
    "give me a break",
    "gives me the creeps",
    "go against the grain",
    "go for broke",
    "go him one better",
    "go out on a limb",
    "go the extra mile",
    "goes without saying",
    "good deed for the day",
    "good things come to those who wait",
    "good time was had by all",
    "grasping at straws",
    "grass is always greener on the other side",
    "greek to me",
    "green thumb",
    "green with envy",
    "green-eyed monster",
    "grist for the mill",
    "guiding light",
    "hair of the dog",
    "happy as a clam",
    "hard to believe",
    "haste makes waste",
    "hat in hand",
    "have a nice day",
    "have your cake and eat it too",
    "head honcho",
    "head over heels",
    "heart's content",
    "heavy heart",
    "hell-bent for leather",
    "hidden agenda",
    "high and the mighty (the)",
    "high on the hog",
    "hindsight is 20/20",
    "hit the books",
    "hit the nail on the head",
    "hit the road",
    "hit the sack",
    "hold a candle to",
    "hold your horses",
    "hold your tongue",
    "hook or by crook",
    "horse of a different color",
    "hot knife through butter",
    "hotter than hell",
    "how goes the battle?",
    "if the shoe fits",
    "if the shoe fits, wear it",
    "if you can't beat 'em, join 'em",
    "ignorance is bliss",
    "in a nutshell",
    "in a pinch",
    "in a wink",
    "in harm's way",
    "in the nick of time",
    "in the tank",
    "in your dreams",
    "in your face",
    "inexorably drawn",
    "influence peddling",
    "info dump",
    "intents and purposes",
    "it ain't over till the fat lady sings",
    "it takes one to know one",
    "it was a dark and stormy night",
    "it won't fly",
    "it's a small world",
    "it's not rocket science",
    "jockey for position",
    "joined at the hip",
    "jump down your throat",
    "jump her/his bones",
    "jump in with both feet",
    "jump on the bandwagon",
    "jump the gun",
    "junk in the trunk",
    "jury is still out",
    "just what the doctor ordered",
    "justice is blind",
    "keep an eye on you",
    "keep it down",
    "keep it simple, stupid",
    "keep up with the Joneses",
    "keep your cards close to vest",
    "keep your chin up",
    "keep your fingers crossed",
    "keep your powder dry",
    "kick ass",
    "kick the bucket",
    "kick up your heels",
    "kick you to the curb",
    "kick your feet up",
    "kickbutt",
    "kid in a candy store",
    "kill two birds with one stone",
    "king's ransom",
    "kiss and tell",
    "kiss ass",
    "kiss of death",
    "kit and kaboodle",
    "knee-high to a grasshopper",
    "knock it out of the park",
    "knock on wood",
    "knock your socks off",
    "knocked up",
    "know him from Adam",
    "know the ropes",
    "know the score",
    "knuckle down",
    "knuckle sandwich",
    "knuckle under",
    "labor of love",
    "lap of luxury",
    "last but not least",
    "last hurrah",
    "last straw",
    "last-ditch effort",
    "law of the jungle",
    "law of the land",
    "lay down the law",
    "leaps and bounds",
    "let bygones be bygones",
    "let sleeping dogs lie",
    "let the cat out of the bag",
    "let your hair down",
    "let's split",
    "level playing field",
    "liberal media",
    "lick your wounds",
    "lie like a rug",
    "life and limb",
    "life imitates art",
    "life is like a box of chocolates",
    "life's a bitch",
    "light at the end of the tunnel",
    "lighten up",
    "lights out",
    "like a moth to a flame",
    "like a sore thumb",
    "like butter",
    "like father, like son",
    "like the plague",
    "like there's no tomorrow",
    "lion's share",
    "litmus test",
    "little black book",
    "live and learn",
    "long and short of it",
    "long in the tooth",
    "long lost love",
    "look before you leap",
    "lounge lizard",
    "love is blind",
    "loved and lost",
    "low man on the totem pole",
    "low-hanging fruit",
    "luck of the Irish",
    "luck of the draw",
    "mad as a hatter",
    "make a long story short",
    "make ends meet",
    "make hay while the sun shines",
    "make lemonade out of lemons",
    "make my day",
    "male chauvinist",
    "man's best friend",
    "many moons",
    "many-splendored thing",
    "mark my words",
    "meaningful relationship",
    "mellow out",
    "method to my madness",
    "mightier than the sword",
    "misery loves company",
    "moment of glory",
    "moment of truth",
    "moment's respite",
    "money doesn't grow on trees",
    "monkey see, monkey do",
    "monkey suit",
    "more than you can shake a stick at",
    "motherhood and apple pie",
    "movers and shakers",
    "moving experience",
    "my two cents",
    "neat as a pin",
    "needle in a haystack",
    "needless to say",
    "never say never",
    "nip it in the bud",
    "no guts, no glory",
    "no love lost",
    "no pain, no gain",
    "no stone unturned",
    "no time like the present",
    "nose to the grindstone",
    "not in my back yard",
    "not on your tintype",
    "not the sharpest tool in the shed",
    "nothing ventured, nothing gained",
    "number one fan",
    "numerous to mention",
    "off the top of my head",
    "off the wagon",
    "old as the hills",
    "old college try",
    "old meets new",
    "older and wiser",
    "older than Methuselah",
    "older than dirt",
    "on the bandwagon",
    "on the nose",
    "on the same page",
    "on the wagon",
    "on thin ice",
    "once in a blue moon",
    "one born every minute",
    "one foot in the grave",
    "one in a million",
    "only game in town",
    "only to be met",
    "opportunity knocks",
    "out of pocket",
    "out of the blue",
    "out of the frying pan",
    "out on a limb",
    "over the moon",
    "p's and q's",
    "pain and suffering",
    "panic button",
    "par for the course",
    "party pooper",
    "pass the sniff test",
    "patience is a virtue",
    "patter of little feet",
    "pay through the nose",
    "peas in a pod",
    "perfect storm",
    "pig in a poke",
    "pillar of society",
    "pinko",
    "play it by ear",
    "playing with fire",
    "plenty of fish in the sea",
    "poison pen",
    "poor as a churchmouse",
    "poor excuse for",
    "pot calling the kettle black",
    "practice what you preach",
    "pretty as a picture",
    "proud possessor",
    "pull out all the stops",
    "pulling your leg",
    "put a sock in it",
    "put my/your foot down",
    "put your best foot forward",
    "put your money where your mouth is",
    "quick and the dead",
    "quick as a bunny",
    "radical chic",
    "rags to riches",
    "raining buckets",
    "raining cats and dogs",
    "rank and file",
    "read between the lines",
    "read my lips",
    "red herring",
    "redheaded stepchild",
    "reign supreme",
    "reinvent the wheel",
    "remember the alamo",
    "rise and shine",
    "road to hell is paved with good intentions",
    "rob Peter to pay Paul",
    "rock and a hard place",
    "rocket science/scientist",
    "rope a dope",
    "rosy-fingered dawn",
    "rub salt in the wound",
    "run for your money",
    "run it up the flagpole",
    "run like the wind",
    "running dog lackey",
    "safe than sorry",
    "salt of the earth",
    "save face",
    "saved by the bell",
    "scapegoat",
    "scared stiff",
    "scared to death",
    "school's out",
    "screaming meemies",
    "see eye to eye",
    "seize the day",
    "senses reel",
    "set in stone",
    "set the record straight",
    "shake a stick should of",
    "shoot for the moon",
    "shoot the breeze",
    "shot in the dark",
    "shoulder to the wheel",
    "shouldered his way",
    "shut your trap",
    "sick as a dog",
    "sigh of relief",
    "signed, sealed, and delivered",
    "significant other",
    "silence is golden",
    "sink or swim",
    "six of one, half a dozen of the other",
    "skating on thin ice",
    "sleep like a log",
    "slept like a log",
    "small world",
    "smell the coffee",
    "smooth sailing",
    "snake in the grass",
    "snow job",
    "snug as a bug",
    "snug as a bug in a rug",
    "some of my best friends",
    "something the cat dragged in",
    "spade a spade",
    "spare the rod",
    "spitting image",
    "spring to life",
    "squeaky wheel gets the grease/oil",
    "start from scratch",
    "stick in the mud",
    "stick in your craw",
    "still waters run deep",
    "stop and smell the roses",
    "store bought",
    "stranger than fiction",
    "straw that broke the camel's back",
    "stubborn as a mule",
    "stuff that dreams are made of",
    "stuffed shirt",
    "take one for the team",
    "take the bull by the horns",
    "take the plunge",
    "takes one to know one",
    "talk turkey",
    "ten foot pole",
    "the earth moved",
    "the final analysis",
    "the real McCoy",
    "the same old story",
    "these things happen",
    "thick as thieves",
    "think outside of the box",
    "third time's the charm",
    "this day and age",
    "this point in time",
    "three strikes and you're out",
    "through the grapevine",
    "throw in the towel",
    "tiger by the tail",
    "till the fat lady sings",
    "time and time again",
    "time is of the essense",
    "tip of the iceberg",
    "to err is human",
    "to the best of my knowledge",
    "tongue-in-cheek",
    "too hot to handle",
    "touch of blarney",
    "tough as nails",
    "tough luck",
    "tough row to hoe",
    "traditional family values",
    "trials and tribulations",
    "tried and true",
    "trip down memory lane",
    "true blue",
    "turn your smile/frown upside-down",
    "twist of fate",
    "twists and turns",
    "two to tango",
    "under the gun",
    "under the same roof",
    "understated elegance",
    "unexpected twist",
    "until the cows come home",
    "up his sleeve",
    "up the creek",
    "up the wrong tree",
    "very real concern",
    "view with alarm",
    "wakeup call",
    "was my face red",
    "watch your tongue",
    "web of intrigue",
    "week of sundays",
    "what a bummer",
    "what comes around, goes around",
    "what the cat dragged in",
    "what the dickens",
    "what the heck/hell",
    "what you see is what you get",
    "what's not to like",
    "wheeler-dealer",
    "when in doubt, punt",
    "when push comes to shove",
    "when rubber meets the road",
    "when the cat's away",
    "when the going gets tough, the tough get going",
    "who has everything",
    "whole ball of wax",
    "whole hog",
    "whole nine yards",
    "whole other story",
    "wild goose chase",
    "wild oats",
    "will wonders never cease",
    "wimp",
    "win friends and influence people",
    "win one for the Gipper",
    "wisdom of the ages",
    "without benefit of clergy",
    "wnning is everything",
    "wolf at the door",
    "words fail",
    "work like a dog",
    "worst nightmare",
    "wrong side of the bed",
    "years young",
    "yellow journalism",
    "you are what you eat",
    "you can run, but you can't hide",
    "you know what they say",
    "young and foolish",
    "young and restless",
    "yuppie",
]